%% CONTROLS
nControls = 20;
u       = ones(nControls,1)*0.1;
u(nControls-1,:) =  0.1;
u(nControls,:)   = -0.1;


u_sca = ones(size(u)).*0.0625; 
u_sca(nControls-1) = 0.125; 
u_sca(nControls) = 0.125; 

assert(nControlsExo == 2,'Update the control vector with the new exo controls');

u_min   = zeros(nControls,1); 
u_min(nControls-1) = -1;
u_min(nControls)   = -1;

u_max   = ones(nControls,1);


u_name  = {...
  '> ControlRightHipExtensionRotY',...
  'ControlRightHipFlexionRotY',...
  'ControlRightKneeExtensionRotY',...
  'ControlRightKneeFlexionRotY',...
  'ControlRightAnkleExtensionRotY',...
  'ControlRightAnkleFlexionRotY',...
  'ControlMiddleTrunkExtensionRotY',...
  'ControlMiddleTrunkFlexionRotY',...
  'ControlUpperTrunkExtensionRotY',...
  'ControlUpperTrunkFlexionRotY',...
  '> ControlHeadExtensionRotY',...
  'ControlHeadFlexionRotY',...
  'ControlRightUpperArmExtensionRotY',...
  'ControlRightUpperArmFlexionRotY',...
  'ControlRightLowerArmExtensionRotY',...
  'ControlRightLowerArmFlexionRotY',...
  'ControlRightHandExtensionRotY',...
  'ControlRightHandFlexionRotY',...
  'ControlExoRightHipRotY',...
  'ControlExoTorsoBarRotY',};
